### ISSUE TITLE
Basic Player Movement

### ISSUE THREAD

**Issue by Cipppp** [Pixel-Arcane/Mystery-Island#1]
**Description:**

Implement basic player movement using Unreal Engine's character controller. The player should be able to move forward, backward, and strafe left and right. Use WASD keys for movement and the mouse to control the camera rotation.

**Tasks:**

- Set up a basic character blueprint.
- Configure input mappings for movement.
- Implement movement logic in the character blueprint.
- Test movement in the game environment.

**Comment by Robyy1** [comment]
do you want first person or third person?

**Comment by Cipppp** [comment]
> do you want first person or third person?

third person
